{
    "name" : "Amazon B2B Connector",
    'version': '1.0.0',
    'category': 'Sales/Sales',
    'sequence': 5,
    'summary': 'Amazon B2B Connector',
    'description': """Amazon B2B Connector""",
    'website': '',
    "depends": ['sale','account','odoo_mirakl_integration'],
    "data": [
        "security/ir.model.access.csv",
        "data/data.xml",
        "views/amazon_b2b_order.xml",
        "views/shop.xml",
        "views/sale.xml",
        "views/res_partner.xml",
        "views/action.xml",
        "views/menu.xml",
    ],
    "application": True,
    "installable": True,
    'license': 'LGPL-3',
}
