from . import res_partner
from . import sale
from . import seller
from . import cdiscount_stock
from . import cdiscount_orders
from . import marketplace_order_tracking
from . import stock_picking
from . import shop_offers
from . import carrier
