{
    "name" : "Everstox Connector",
    'version': '1.0.0',
    'category': 'Sales/Sales',
    'sequence': 5,
    'summary': 'Everstox Connector',
    'description': """Everstox Connector""",
    'website': '',
    "depends": ['sale','account','odoo_mirakl_integration'],
    "data": [
        "security/ir.model.access.csv",
        "views/product.xml",
        "views/fulfillment.xml",
        "views/shipment.xml",
        "views/return.xml",
        "views/transfers.xml",
        "views/purchase.xml",
        "views/warehouse_product_unit.xml",
        "views/warehouse_product.xml",
        "views/warehouse_sale_orders.xml",
        "views/warehouse_stock.xml",
        "views/warehouse_stock_updates.xml",
        "views/warehouse_processed_order.xml",
        "views/shop.xml",
        "views/action.xml",
        "views/menu.xml",
        "wizard/notification_wizard.xml",
    ],
    "application": True,
    "installable": True,
    'license': 'LGPL-3',
}
