# -*- coding: utf-8 -*-
{
    'name': 'Mirakl Integration',
    'version': '1.0.2',
    'category': 'Sales/Sales',
    'sequence': 5,
    'summary': 'Odoo Mirakl Integration',
    'description': """Odoo Mirakl Integration""",
    'website': '',
    'depends': ['base', 'sale_management', 'stock', 'account_accountant', 'purchase', 'sale'],
    'data': [
        'security/ir.model.access.csv',
        'views/marketplace_warehouse.xml',
        'views/marketplace_vendor.xml',
        'views/marketplace_product.xml',
        'views/marketplace_order_tracking.xml',
        'views/processed_orders.xml',
        'views/sale_order.xml',
        'views/warehouse_purchase_order.xml',
        'views/warehouse_price.xml',
        'views/warehouse_inventory.xml',
        'views/mirakl_stock.xml',
        'views/logs_info.xml',
        'views/shop.xml',
        'views/delivery.xml',
        'views/product.xml',
        'views/mirakl_offers.xml',
        'views/mirakl_carriers.xml',
        'wizard/notification_wizard.xml',
        'wizard/bulk_inventory_update.xml',
        'wizard/shop_offers.xml',
        'wizard/order_changes.xml',
        'views/actions.xml',
        'views/menus.xml',
        'report/purchase_order_template.xml'
    ],
    'application': True,
    'installable': True,
    'license': 'LGPL-3',
}
